# Dockerfile.celery

FROM python:3.10-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# This makes the model files part of the image, ensuring they are always available.
COPY ./models /app/models

# Copy application code
COPY . .

# The CMD is defined in the docker-compose.yml file, allowing this image
# to be used for both the 'worker' and 'beat' services.